name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Rrust
      run: rustup update
    - name: Download CoppeliaSim
      run: wget https://coppeliarobotics.com/files/beta/CoppeliaSim_Edu_V4_6_0_rev0_Ubuntu22_04.tar.xz
    - name: Extract CoppeliaSima
      run: tar -xf CoppeliaSim_Edu_V4_6_0_rev0_Ubuntu22_04.tar.xz
    - name: Running Simulator
      run: ./CoppeliaSim_Edu_V4_6_0_rev0_Ubuntu22_04/coppeliaSim.sh -h &
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    # - name: Check format
    #   run: cargo fmt --verbose; git diff-index --exit-code HEAD -- .
     
